# TensorFlow
    TensorFlow is an open source library for numerical computation using data flow graphs

TensorFlow can be described with a data model, a programming model, and an execution
model:
* <b>Data</b> model comprises of tensors, that are the basic data units created,
manipulated, and saved in a TensorFlow program.
* <b>Programming</b> model comprises of data flow graphs or computation graphs.
Creating a program in TensorFlow means building one or more TensorFlow
computation graphs.
* <b>Execution</b> model consists of firing the nodes of a computation graph in a
sequence of dependence. The execution starts by running the nodes that are
directly connected to inputs and only depend on inputs being present.

TensorFlow APIs or libraries are divided into two levels:
* <b>Lower-level library</b>: The lower level library, also known as TensorFlow core,
provides very fine-grained lower level functionality, thereby offering complete
control on how to use and implement the library in the models. We will cover
TensorFlow core in this chapter.
* <b>Higher-level libraries</b>: These libraries provide high-level functionalities and are
comparatively easier to learn and implement in the models. Some of the libraries
include TF Estimators, TFLearn, TFSlim, Sonnet, and Keras. We will cover some
of these libraries in the next chapter.

# TensorFlow Core
A tensor can have any number of dimensions:
* <b>scalar</b>: a zero-dimensional collection(tensor rank 0)
* <b>vaector</b>: a one-dimensional collection(tensor rank 1)
* <b>matrix</b>: a two-dimensional collection(tensor rank 2)
* <b>tensor</b>: multidimensional collection(tensor rank >2)


## Tensors
    * Constants
    * Placeholders
    * Operations
    * Creating tensors from Python objects
    * Variables
    * Tensors generated from library functions

In [2]:
import tensorflow as tf
import numpy as np

# Get an Interactive TensorFlow Session 

In [3]:
sess = tf.InteractiveSession()

# Customary Hello TensorFlow !!!

In [5]:
hello = tf.constant("Hello TensorFlow !!")
print(sess.run(hello))

b'Hello TensorFlow !!'


# Constants

In [9]:
c1 = tf.constant(value=5, name='x')
c2 = tf.constant(value=6.0, name='x')
c3 = tf.constant(value=7.0, dtype=tf.float32, name='z')
print('c1 (x): ', c1)
print('c2 (y): ', c2)
print('c3 (z): ', c3)

c1 (x):  Tensor("x_2:0", shape=(), dtype=int32)
c2 (y):  Tensor("x_3:0", shape=(), dtype=float32)
c3 (z):  Tensor("z_3:0", shape=(), dtype=float32)


In [6]:
print('run([c1,c2,c3]) : ', sess.run([c1, c2, c3]))

run([c1,c2,c3]) :  [5, 6.0, 7.0]


<img src="images/data_types.PNG">
          

# Operations

In [12]:
op1 = tf.add(c2, c3)
op2 = tf.multiply(c2, c3)
print('op1 : ', op1)
print('op2 : ', op2)

op1 :  Tensor("Add_1:0", shape=(), dtype=float32)
op2 :  Tensor("Mul_2:0", shape=(), dtype=float32)


In [8]:
print('run(op1) : ', sess.run(op1))
print('run(op2) : ', sess.run(op2))

run(op1) :  13.0
run(op2) :  42.0


<img src="images/operations.PNG">

# Placeholders
Constants allow us to provide a value at the time of defining the tensor, the
placeholders allow us to create tensors whose values can be provided at runtime.

In [22]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
print('p1 : ', p1)
print('p2 : ', p2)

p1 :  Tensor("Placeholder:0", dtype=float32)
p2 :  Tensor("Placeholder_1:0", dtype=float32)


In [23]:
op4 = p1 * p2  # shorthand for tf.multiply(p1, p2)

In [25]:
print('run(op4,{p1:2.0, p2:3.0}) : ',sess.run(op4, feed_dict={p1:2.0, p2:3.0}))

run(op4,{p1:2.0, p2:3.0}) :  6.0


In [26]:
print('run(op4,feed_dict = {p1:3.0, p2:4.0}) : ',
      sess.run(op4, feed_dict={p1: 3.0, p2: 4.0}))

run(op4,feed_dict = {p1:3.0, p2:4.0}) :  12.0


In [27]:
print('run(op4,feed_dict={p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}):',
      sess.run(op4, feed_dict={p1: [2.0, 3.0, 4.0], p2: [3.0, 4.0, 5.0]}))

run(op4,feed_dict={p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}): [ 6. 12. 20.]


# Creating Tensors from Existing Objects

## 0-Dimensional Tensors (Scalars)

In [28]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)

print('tf_t : ', tf_t)
print('run(tf_t) : \n', sess.run(tf_t))

tf_t :  Tensor("Const_2:0", shape=(), dtype=float64)
run(tf_t) : 
 5.0


## 1-Dimensional Tensors (Vectors)

In [30]:
a1dim = np.array([1, 2, 3, 4, 5.99])
print("a1dim Shape : ", a1dim.shape)

tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0] : ', tf_t[0])
print('tf_t[0] : ', tf_t[2])
print('run(tf_t) : \n', sess.run(tf_t))

a1dim Shape :  (5,)
tf_t :  Tensor("Const_4:0", shape=(5,), dtype=float64)
tf_t[0] :  Tensor("strided_slice_2:0", shape=(), dtype=float64)
tf_t[0] :  Tensor("strided_slice_3:0", shape=(), dtype=float64)
run(tf_t) : 
 [1.   2.   3.   4.   5.99]


## 2-Dimensional Tensors (Matrices)

In [15]:
a2dim = np.array([(1, 2, 3, 4, 5.99),
                  (2, 3, 4, 5, 6.99),
                  (3, 4, 5, 6, 7.99)
                  ])
print("a2dim Shape : ", a2dim.shape)

tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0] : ', tf_t[0][0])
print('tf_t[1][2] : ', tf_t[1][2])
print('run(tf_t) : \n', sess.run(tf_t))

a2dim Shape :  (3, 5)
tf_t :  Tensor("Const_3:0", shape=(3, 5), dtype=float64)
tf_t[0][0] :  Tensor("strided_slice_3:0", shape=(), dtype=float64)
tf_t[1][2] :  Tensor("strided_slice_5:0", shape=(), dtype=float64)
run(tf_t) : 
 [[ 1.    2.    3.    4.    5.99]
 [ 2.    3.    4.    5.    6.99]
 [ 3.    4.    5.    6.    7.99]]


## 3-Dimensional Tensors

In [16]:
a3dim = np.array([[[1, 2],
                   [3, 4]
                   ],
                  [[5, 6],
                   [7, 8]
                   ]
                  ])
print("a3dim Shape : ", a3dim.shape)

tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0][0] : ', tf_t[0][0][0])
print('tf_t[1][1][1] : ', tf_t[1][1][1])
print('run(tf_t) : \n', sess.run(tf_t))

a3dim Shape :  (2, 2, 2)
tf_t :  Tensor("Const_4:0", shape=(2, 2, 2), dtype=float64)
tf_t[0][0][0] :  Tensor("strided_slice_8:0", shape=(), dtype=float64)
tf_t[1][1][1] :  Tensor("strided_slice_11:0", shape=(), dtype=float64)
run(tf_t) : 
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]]


# Variables
In TensorFlow, variables are tensor objects that hold values that can be modified during the
execution of the program.

In [14]:
# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.3], tf.float32, name='w')
b = tf.Variable([-.3], tf.float32)
# Define model input and output
x = tf.placeholder(tf.float32)
y = w * x + b

print("w:", w)
print("x:", x)
print("b:", b)
print("y:", y)

w: <tf.Variable 'w:0' shape=(1,) dtype=float32_ref>
x: Tensor("Placeholder:0", dtype=float32)
b: <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>
y: Tensor("add_2:0", dtype=float32)


In [15]:
# initialize and print the variable y
tf.global_variables_initializer().run()
print('run(y,{x:[1,2,3,4]}) : ', sess.run(y,feed_dict= {x: [1, 2, 3, 4]}))

run(y,{x:[1,2,3,4]}) :  [0.         0.3        0.6        0.90000004]


<img src="images/variables_placeholders.PNG">

# Creating Tensors from Library Functions

In [16]:
a = tf.zeros((100,))
print(sess.run(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


# Close the interactive session

In [19]:
sess.close()

# Computation Graphs

## Building and Running simple computation graph
The only difference between Session() and InteractiveSession() is
that the session created with InteractiveSession() becomes the
default session. Thus, we do not need to specify the session context to
execute the session-related command later. For example, say that we have
a session object, sess, and a constant object, hello. If sess is an
InteractiveSession() object, then we can evaluate hello with the
code hello.eval(). If sess is a Session() object, then we have to
use either sess.hello.eval() or a with block.

In [20]:
# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Define model input and output
x = tf.placeholder(tf.float32)
y = w * x + b
with tf.Session() as sess:
    # initialize and print the variable y
    sess.run(tf.global_variables_initializer())
    output = sess.run(y, {x: [1, 2, 3, 4]})
print('output : ', output)

output :  [0.         0.3        0.6        0.90000004]


# TensorBoard

In [1]:
import tensorflow as tf
import numpy as np

# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.3], name='w', dtype=tf.float32)
b = tf.Variable([-.3], name='b', dtype=tf.float32)
# Define model input and output
x = tf.placeholder(name='x', dtype=tf.float32)
y = w * x + b

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    writer = tf.summary.FileWriter('tflogs_02', sess.graph)
    print('run(y,{x:3}) : ', sess.run(y, feed_dict={x: 3}))

run(y,{x:3}) :  [0.6]


In [26]:
# execute: tensorboard --logdir=logs

*:)*