In [1]:
import numpy as np

### How to create an 1d_array

In [4]:
a = np.array((1,2,3,4,5))
a

array([1, 2, 3, 4, 5])

In [5]:
a.dtype

dtype('int32')

#### Set dtype explicity

In [6]:
n = [1,2,3,4,5]
type(n[0])

int

In [7]:
a = np.array([1,2,3,4,5],dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [8]:
a.ndim, a.shape, a.size , a.dtype, a.sum(), a.argsort()

(1, (5,), 5, dtype('float64'), 15.0, array([0, 1, 2, 3, 4], dtype=int64))

In [9]:
a = a.astype(np.float32) # a.astype('float32')
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [10]:
a.dtype

dtype('float32')

### How to create an nd_array

In [11]:
lst = [[1,2,3,4,5],[6,7,8,9,10]]
lst

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [12]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [13]:
b.dtype

dtype('float64')

In [14]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

### Reshape

In [17]:
array = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]],dtype=np.float64)
array

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])

In [18]:
array.shape

(2, 6)

In [63]:
np.reshape(array,newshape=[6,2])

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]])

In [21]:
array.size

12

In [26]:
reshaped_array = np.reshape(array,newshape=[2,3,-1])
reshaped_array

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]])

In [23]:
reshaped_array.shape

(2, 3, 2)

In [32]:
reshaped_array = np.reshape(array,newshape=[2,-1,2])
reshaped_array

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]])

In [28]:
reshaped_array.shape

(2, 3, 2)

### Methods of numpy

In [24]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.empty((4,4)) 

array([[2.37663529e-312, 2.58883487e-312, 2.41907520e-312,
        2.44029516e-312],
       [2.44029516e-312, 2.05833592e-312, 2.14321575e-312,
        8.48798317e-313],
       [9.33678148e-313, 8.70018275e-313, 2.35541533e-312,
        2.12199579e-312],
       [2.41907520e-312, 8.27578359e-313, 8.27578359e-313,
        2.22522596e-306]])

In [26]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [30]:
np.random.standard_normal((2,3))

array([[-0.2024873 ,  0.01104034,  0.43303952],
       [ 0.68477227,  1.35043495,  0.86543927]])

In [37]:
a = np.random.multivariate_normal(mean=[1,1],cov=0.01 * np.eye(2),size=(50,))
a.shape

(50, 2)

### Axis

In [38]:
array = np.random.standard_normal((2,3))
array

array([[-1.38831127,  1.25651759,  0.74804007],
       [ 1.52857796,  0.67415529, -1.31390139]])

In [5]:
np.sum(array,axis=1)

array([-2.11228348,  2.3956633 ])

In [7]:
sum([-0.79441283,  0.24852512, -1.56639577]) , sum([ 1.17892706,  1.26351743, -0.04678119])

(-2.11228348, 2.3956633)

In [8]:
np.mean(array, axis=0)

array([ 0.19225711,  0.75602127, -0.80658848])

### stacking

In [39]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

In [128]:
np.vstack([a,b]) # number of columns does not change...

array([[ 0.84292811, -0.86347996, -0.52361013],
       [ 0.26750922,  0.2182274 , -0.83793808],
       [ 0.47527915, -1.1574155 ,  0.37682874],
       [ 0.3123485 ,  1.59407874,  0.36642956]])

In [41]:
np.hstack([a,b]) # number of rows does not change...

array([[-0.84980565,  0.49434804,  0.16077597,  0.90519453, -0.21449692,
         0.4761655 ],
       [-0.2385852 , -0.66078054,  0.20754627,  0.26253823,  1.312964  ,
        -0.39488402]])

In [46]:
np.concatenate([a,b])

array([[-1.06530156, -0.56622031,  0.66045807],
       [ 0.73137132, -0.81999493,  0.37125394],
       [ 0.77215741, -0.24932539,  0.85472829],
       [ 0.26395366, -0.62911961, -1.07168362]])

In [47]:
a.transpose()

array([[-1.06530156,  0.73137132],
       [-0.56622031, -0.81999493],
       [ 0.66045807,  0.37125394]])

In [48]:
a.T

array([[-1.06530156,  0.73137132],
       [-0.56622031, -0.81999493],
       [ 0.66045807,  0.37125394]])

In [49]:
np.save('example.npy',a)

In [50]:
a1 = np.load('example.npy')

In [51]:
a1

array([[-1.06530156, -0.56622031,  0.66045807],
       [ 0.73137132, -0.81999493,  0.37125394]])

In [57]:
np.allclose(a,a1)

True

### Check the speed of arrays

In [2]:
import numpy as np
a = np.linspace(0,100,1000000)
b = np.linspace(0,100,1000000)

In [3]:
a.size

1000000

In [3]:
def get_dot(a,b):
    c = 0
    for i in range(1000000):
        c += a[i] * b[i]
    return c

In [4]:
%timeit get_dot(a,b)

639 ms ± 69.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
res = np.dot(a,b)
res

3333335000.001665

In [6]:
get_dot(a,b)

3333335000.001634

In [7]:
%timeit np.dot(a,b)

1.27 ms ± 22.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
639  / 1.27

503.14960629921256

### broadcasting

In [46]:
v = np.linspace(0,10,5)
v + 1

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [47]:
ones = np.ones((6,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
twos = np.ones((6,1)) * 2
twos

array([[2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.]])

In [52]:
ones.shape, twos.shape

((6, 5), (6, 1))

In [53]:
ones + twos

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

*:)*