In [40]:
import numpy as np

In [41]:
v = np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [42]:
v[0]

0.0

In [43]:
v[1]

2.5

In [44]:
v[-1]

10.0

In [45]:
v[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [46]:
vv = np.random.random((5,4))

In [47]:
vv

array([[0.6440016 , 0.18234613, 0.91390469, 0.89922484],
       [0.77316825, 0.44729373, 0.90862357, 0.92350986],
       [0.38621451, 0.80812977, 0.14537204, 0.20295736],
       [0.56265572, 0.75992846, 0.10911574, 0.51470711],
       [0.51573392, 0.35364653, 0.05864034, 0.23587904]])

In [48]:
vv[0,0]

0.6440015950028937

In [49]:
vv[4,3]

0.23587904433496953

In [50]:
ll = [[1,2,3],[4,5,6],[7,8,9]]

In [52]:
ll[1,2]

TypeError: list indices must be integers or slices, not tuple

In [53]:
ll[1][2]

6

In [55]:
v[2:4]

array([5. , 7.5])

In [18]:
vv[2:5,1]

array([0.72994472, 0.85984031, 0.21626174])

In [19]:
vv[2:5,1:2]

array([[0.72994472],
       [0.85984031],
       [0.21626174]])

In [20]:
vv[2:-1,:]

array([[0.02059223, 0.72994472, 0.71362606, 0.77533239],
       [0.9038464 , 0.85984031, 0.94464557, 0.72122998]])

In [22]:
vv[:,::2]

array([[0.18210264, 0.98438833],
       [0.58132127, 0.88356747],
       [0.02059223, 0.71362606],
       [0.9038464 , 0.94464557],
       [0.32609565, 0.47702323]])

# Mutables

In [23]:
v2 = v[2:4]

In [24]:
v2

array([5. , 7.5])

In [25]:
v2[0] = 0

In [30]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [31]:
v3 = v[2:4].copy()

In [32]:
v3[0] = 1

In [33]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

### boolean mask

In [56]:
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [59]:
v[[0,2,4]]

array([ 0.,  5., 10.])

In [60]:
bool_index = v > 0
bool_index

array([False,  True,  True,  True,  True])

In [61]:
v[bool_index]

array([ 2.5,  5. ,  7.5, 10. ])

In [62]:
vv

array([[0.6440016 , 0.18234613, 0.91390469, 0.89922484],
       [0.77316825, 0.44729373, 0.90862357, 0.92350986],
       [0.38621451, 0.80812977, 0.14537204, 0.20295736],
       [0.56265572, 0.75992846, 0.10911574, 0.51470711],
       [0.51573392, 0.35364653, 0.05864034, 0.23587904]])

In [63]:
vv[vv > 0.5] = vv[vv > 0.5] * 2

In [64]:
vv

array([[1.28800319, 0.18234613, 1.82780939, 1.79844969],
       [1.54633649, 0.44729373, 1.81724714, 1.84701971],
       [0.38621451, 1.61625955, 0.14537204, 0.20295736],
       [1.12531144, 1.51985693, 0.10911574, 1.02941422],
       [1.03146785, 0.35364653, 0.05864034, 0.23587904]])

In [65]:
vv[vv > 0.5] = 0.0
vv

array([[0.        , 0.18234613, 0.        , 0.        ],
       [0.        , 0.44729373, 0.        , 0.        ],
       [0.38621451, 0.        , 0.14537204, 0.20295736],
       [0.        , 0.        , 0.10911574, 0.        ],
       [0.        , 0.35364653, 0.05864034, 0.23587904]])

In [66]:
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [69]:
v[[0,3]] = [4,5]
v

array([ 4.,  5.,  5.,  5., 10.])

*:)*