In [1]:
import numpy as np

In [12]:
array = np.random.standard_normal((4,5))
array

array([[-0.36713199, -0.75928252, -0.96936324, -0.14613024, -0.8851043 ],
       [ 2.16348045, -0.23558594, -0.8593813 ,  2.91080246, -1.7028278 ],
       [-0.51867437,  0.49900126,  0.885237  ,  1.50554699, -0.35848382],
       [ 1.57698425, -0.55300313, -0.32790432,  0.65558624, -0.33772899]])

In [19]:
array.reshape((20,))

array([-0.36713199, -0.75928252, -0.96936324, -0.14613024, -0.8851043 ,
        2.16348045, -0.23558594, -0.8593813 ,  2.91080246, -1.7028278 ,
       -0.51867437,  0.49900126,  0.885237  ,  1.50554699, -0.35848382,
        1.57698425, -0.55300313, -0.32790432,  0.65558624, -0.33772899])

In [7]:
x = np.linspace(0,10,100)
sinx = np.sin(x)
cosx = np.cos(x)

In [20]:
np.dot(sinx,cosx)

1.6882473430775704

In [21]:
ones = np.ones((5,))
ones

array([1., 1., 1., 1., 1.])

In [22]:
line_space = np.linspace(-2, 2, 5)
line_space

array([-2., -1.,  0.,  1.,  2.])

In [23]:
rl = np.outer(ones,line_space)
rl

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

### np.dot

In [27]:
ones = np.ones((6,5)) * 3
ones

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [28]:
ones.shape

(6, 5)

In [29]:
ones_reshaped = ones.reshape(5,6)
ones_reshaped

array([[3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.]])

In [30]:
np.dot(ones_reshaped , ones)

array([[54., 54., 54., 54., 54.],
       [54., 54., 54., 54., 54.],
       [54., 54., 54., 54., 54.],
       [54., 54., 54., 54., 54.],
       [54., 54., 54., 54., 54.]])

### example:

In [32]:
A = np.array([[1,2],[3,5],[7,6]])
p = np.diag([5,5,5])
l = np.array([7,3, 2]).reshape((3,1))


In [33]:
np.dot(np.dot(np.dot(np.linalg.inv(np.dot(np.dot(A.T,p),A)),A.T),p),l)

array([[-1.32485876],
       [ 1.83333333]])

### check the shape and do A'PL

### numpy where

In [9]:
array = np.array([1,2,3,4])
rows = np.where(array >= 2.5)
array[rows]

array([3, 4])

In [6]:
t = np.array([[1,2,3,'foo'],
 [2,3,4,'bar'],
 [5,6,7,'hello'],
 [8,9,1,'bar']])

In [12]:
rows , cols = np.where(t == 'bar')
t[rows]

array([['2', '3', '4', 'bar'],
       ['8', '9', '1', 'bar']], dtype='<U11')

In [14]:
rows, cols

(array([1, 3], dtype=int64), array([3, 3], dtype=int64))

In [15]:
array = np.random.standard_normal((5,5,3))
array

array([[[ 0.51240753,  2.28609226, -0.44117211],
        [ 2.06164266,  1.09456158,  1.22166665],
        [-0.66520789,  1.5000412 ,  1.54596543],
        [ 0.73281986,  3.02937594, -0.95555157],
        [ 0.75733433, -0.84443455,  0.3129516 ]],

       [[ 0.89814288, -0.30968381, -0.23474092],
        [ 0.05880609,  0.02703437,  2.00029908],
        [ 0.74634565,  1.25066639,  2.03310231],
        [ 0.42857288, -0.78326455,  1.01061598],
        [ 0.45741054, -0.74671491,  0.41503907]],

       [[ 0.80335544,  1.12720072, -1.1303238 ],
        [-1.27760025, -1.33987789, -0.35893175],
        [ 0.37256469, -0.06233023,  0.23712224],
        [-0.12688497,  0.22739639,  1.3269323 ],
        [ 0.88241551, -1.28972705, -1.42758318]],

       [[ 1.39777531,  0.45342728, -2.35943149],
        [ 1.65339637,  1.44645747, -0.20487503],
        [-1.7837175 ,  0.97878316, -0.67431872],
        [-1.65441639,  1.70401029,  0.93265948],
        [ 1.04217376,  0.95346608,  1.07123978]],

       [[-0.

In [16]:
rows, cols, heights = np.where(array >= 1)
array[rows, cols, heights]

array([2.28609226, 2.06164266, 1.09456158, 1.22166665, 1.5000412 ,
       1.54596543, 3.02937594, 2.00029908, 1.25066639, 2.03310231,
       1.01061598, 1.12720072, 1.3269323 , 1.39777531, 1.65339637,
       1.44645747, 1.70401029, 1.04217376, 1.07123978, 1.26824649,
       1.24249097])

*:)*