In [1]:
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist
from keras.utils import to_categorical, plot_model
from keras.models import Sequential
from keras.layers import Dense, Softmax, Activation
from keras.optimizers import Adam

Using TensorFlow backend.


In [5]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
image_size = x_train.shape[1]
print(x_train.shape, y_train.shape)
# image_0 = x_train[10]
# plt.imshow(image_0)
# plt.show()

(60000, 28, 28) (60000,)


In [6]:
# hyper paramters
n_outputs = 10 # len(np.unique(y_train))
n_inputs = image_size * image_size
hidden_layers = [256, 256]
activation_function = 'relu'

In [7]:
x_train = x_train.reshape((60000, image_size * image_size))
x_test = x_test.reshape((-1, image_size * image_size))

x_train = x_train.astype('float32')/255
x_test = x_test.astype('float32')/255

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

print(x_train.shape, y_train.shape)
print(y_train[:5])

(60000, 784) (60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [8]:
model = Sequential()
model.add(Dense(units=hidden_layers[0],input_dim=n_inputs,name='hidden_1'))
model.add(Activation(activation=activation_function,name='relu_1'))
model.add(Dense(units=hidden_layers[1],name='hidden_2'))
model.add(Activation(activation=activation_function,name='relu_2'))
model.add(Dense(units=n_outputs,name='output_layer'))
model.add(Activation(activation='softmax',name='soft_max'))
model.summary()
plot_model(model=model,to_file='mnist-mlp.png',show_shapes=True)


model.compile(loss='categorical_crossentropy',optimizer=Adam(lr=0.01),metrics=['acc'])
model_histoty = model.fit(x_train,y_train,epochs=20,batch_size=32)

W0807 11:41:09.028302 14672 deprecation_wrapper.py:119] From D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0807 11:41:09.113643 14672 deprecation_wrapper.py:119] From D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0807 11:41:09.141094 14672 deprecation_wrapper.py:119] From D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



ValueError: Unknown activation function:maxout

In [6]:
model.compile(loss='categorical_crossentropy',optimizer=Adam(lr=0.01),metrics=['acc'])

W0724 19:20:12.182448 12124 deprecation_wrapper.py:119] From D:\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0724 19:20:12.195423 12124 deprecation_wrapper.py:119] From D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [7]:
model_histoty = model.fit(x_train,y_train,epochs=20,batch_size=32)

W0724 19:20:15.891542 12124 deprecation.py:323] From D:\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0724 19:20:15.967383 12124 deprecation_wrapper.py:119] From D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/20
60000/60000 [==============================] - 18s 300us/step - loss: 0.2897 - acc: 0.9183
Epoch 2/20
60000/60000 [==============================] - 22s 369us/step - loss: 0.1924 - acc: 0.9492
Epoch 3/20
60000/60000 [==============================] - 21s 344us/step - loss: 0.1726 - acc: 0.9553
Epoch 4/20
60000/60000 [==============================] - 18s 302us/step - loss: 0.1519 - acc: 0.9605
Epoch 5/20
60000/60000 [==============================] - 17s 286us/step - loss: 0.1440 - acc: 0.9637
Epoch 6/20
60000/60000 [==============================] - 17s 287us/step - loss: 0.1334 - acc: 0.9671
Epoch 7/20
60000/60000 [==============================] - 21s 358us/step - loss: 0.1290 - acc: 0.9678
Epoch 8/20
60000/60000 [==============================] - 21s 350us/step - loss: 0.1248 - acc: 0.9703
Epoch 9/20
60000/60000 [==============================] - 21s 347us/step - loss: 0.1172 - acc: 0.9717
Epoch 10/20
60000/60000 [==============================] - 17s 276us/step - loss: 